GCS Source and Sink additional test cases
sawantpritam/google-cloud pull request #14
Opened 2022-03-02 19:19 UTC by sumitsri12

@sawantpritam Please review

2022-03-03 04:31 UTC, sawantpritam commented
1. Please add proper commit message

2. Your branch is 4 commits behind sawantpritam:e2e-gcs. Please update

2022-03-03 05:27 UTC, sawantpritam requested changes
@sumitsri12

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcs/stepsdesign/GCSSource.java
> +  public void selectFileEncodingType(String encoding) {
-> Select GCS source property file encoding type

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcs/stepsdesign/GCSSource.java
> +  public void selectGCSPropertyReadFileRecursive(String value) {
-> Select GCS source property read file recursive as {string}

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcs/stepsdesign/GCSSource.java
> +  public void selectGCSSourcePropertyPathFilenameOnly(String value) {
-> Select GCS source property path filename only as  {string}

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcs/stepsdesign/GCSSink.java
> +  @Then("Select GCS sink property toggle write header true")
->Toggle GCS sink property write header to true

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcs/stepsdesign/GCSBase.java
> +  @Then("Verify data is transferred to target GCS bucket with fileName {string}")
-> Verify data is transferred to target GCS bucket with fileName prefix

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcs/stepsdesign/GCSBase.java
> +  public void verifyDataIsTransferredToTargetGCSBucketWithFileNamePrefix(String fileName) {
(String fileNamePrefix)

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcs/stepsdesign/GCSBase.java
> +      BeforeActions.scenario.write("Data transferred to gcs bucket " + gcsBucket + " with fileNameContains "
fileNameContains -> file name prefix

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/features/gcs/sink/GCSSink.feature
> +    Then Verify data is transferred to target GCS bucket with fileName "gcsOutputFilePrefix"
-> Verify data is transferred to target GCS bucket with fileName prefix "gcsOutputFilePrefix"

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/features/gcs/sink/GCSSink.feature
> +    Then Verify data is transferred to target GCS bucket with fileName "gcsPathSuffix"
-> Verify data is transferred to target GCS bucket with fileName suffix "gcsPathSuffix"

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcs/stepsdesign/GCSBase.java
> +    try {
Add one more parameter to this method  String filePart  and 
change if condition based on filePart
if (blob.getName().contains(fileNameContains)) {
          return true;
        }

if filePart is "suffix" -> .endsWith
else if filePart is "prefix" -> .startsWith
else if filePart is "contains" -> .contains
else .equals

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +  @Before(order = 1, value = "@GCS_DATATYPE_1_TEST")
Add javadoc with list of datatypes

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +  @Before(order = 1, value = "@GCS_DATATYPE_2_TEST")
Add javadoc with list of datatypes

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +  @Before(order = 1, value = "@GCS_Parquet_TEST")
@GCS_Parquet_TEST -> @GCS_PARQUET_TEST

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +  @Before(order = 1, value = "@GCS_Avro_TEST")
Tag all CAPS

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +    "or @GCS_READ_RECURSIVE_TEST or @GCS_Parquet_TEST or @GCS_Avro_TEST")
TAG ALL CAPS

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/features/gcs/source/GCSSourceAdditionalCases.feature
> +  @GCS_CSV_TEST @BQ_SINK_TEST @GCS_READ_RECURSIVE_TEST
remove @GCS_CSV_TEST

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/features/gcs/source/GCSSourceAdditionalCases.feature
> +  @GCS_CSV_TEST @BQ_SINK_TEST @GCS_DATATYPE_1_TEST
remove @GCS_CSV_TEST 
same comment for all scenarios... remove tags if not required for that scenario

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/features/gcs/source/GCSSourceAdditionalCases.feature
> +  @GCS_CSV_TEST @BQ_SINK_TEST @encoding
what is @encoding

2022-03-03 05:27 UTC, sawantpritam commented on src/e2e-test/features/gcs/source/GCSSourceAdditionalCases.feature
> +      | encodingType |
encodingType -> EncodingType

2022-03-03 07:08 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcs/stepsdesign/GCSBase.java
> +  @Then("Verify data is transferred to target GCS bucket with fileName {string}")
I am using this method in both prefix and suffix

2022-03-03 16:07 UTC, sumitsri12 commented
@sawantpritam  pushed after changes

2022-03-03 17:21 UTC, sawantpritam requested changes

2022-03-03 17:21 UTC, sawantpritam commented on src/e2e-test/features/gcs/source/GCSSourceAdditionalCases.feature
> +
remove extra line

2022-03-03 17:21 UTC, sawantpritam commented on src/e2e-test/features/gcs/source/GCSSourceAdditionalCases.feature
> +@GCS_Source
Rename file name - > GCSSourceToBigQueryAdditionalTests.feature

2022-03-03 17:21 UTC, sawantpritam commented on src/e2e-test/features/gcs/source/GCSSourceAdditionalCases.feature
> +
remove extra line

2022-03-03 17:21 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> + /** create gcs bucket with csv file containing below datatypes.
-> Create GCS 

Also check formatting.... * on each line

2022-03-03 17:21 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +  /** create gcs bucket with csv file containing below datatypes.
Similar comment as above

2022-03-03 17:21 UTC, sawantpritam commented on src/e2e-test/resources/pluginParameters.properties
> +gcsParquetFile=testdata/GCS_Parquet_TEST.parquet
This should match with filename in testdata folder

2022-03-04 13:31 UTC, sawantpritam requested changes

2022-03-04 13:31 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcs/runners/sourcerunner/TestRunner.java
> +public class TestRunner1 {
Rename

2022-03-04 13:31 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcs/runners/sinkrunner/TestRunner.java
> +public class TestRunner1 {
Rename

2022-03-08 07:55 UTC, sawantpritam approved these changes

2022-03-08 07:56 UTC, sawantpritam commented
Squash the commits.

2022-03-09 06:26 UTC, closed without merging