BigQuery
sawantpritam/google-cloud pull request #15
Opened 2022-03-07 17:18 UTC by itsmekumari

@sawantpritam Please review the BigQuery changes.

2022-03-08 06:26 UTC, sawantpritam commented
Please add proper PR title and proper commit message.

2022-03-08 07:58 UTC, sawantpritam requested changes

2022-03-08 07:58 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +  @Before(order = 1, value = "@BQ_SOURCE_DATATYPE_TEST")
Add java doc comment - with list of datatypes

2022-03-08 07:58 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigquery/stepsdesign/BigQuerySource.java
> +  public void enterTheBigQuerySourcePropertyForViewMaterializationProject(String projectId) {
projectId -> viewMaterializationProject

2022-03-08 07:58 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigquery/stepsdesign/BigQuerySource.java
> +  public void enterTheBigQuerySourcePropertyForViewMaterializationDataset(String dataset) {
dataset -> viewMaterializationDataset

2022-03-08 07:58 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigquery/stepsdesign/BigQuerySink.java
> +    @Then("Verify the validation error message for invalid chunk size")
Create parameterised common step definition in BigQueryBase-
Verify the BigQuery validation error message for invalid property {string}

2022-03-08 07:58 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigquery/stepsdesign/BigQuerySink.java
> +  @Then("Verify the validation error message for invalid dataset")
Utilise common step definition

2022-03-08 07:58 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigquery/stepsdesign/BigQuerySink.java
> +  @Then("Verify the validation error message for invalid table")
Utilise common step definition

2022-03-08 07:58 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigquery/stepsdesign/BigQueryBase.java
> +  @Then("Verify the validation error message for invalid temporary bucket")
Utilise common step definition

2022-03-08 07:58 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigquery/stepsdesign/BigQueryBase.java
> +  @And("Wait for page to render properly")
Remove.

2022-03-08 07:58 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigquery/stepsdesign/BigQuerySink.java
> +  @Then("Enter the BigQuery sink properties with incorrect Dataset {string}")
Remove.
Use existing- Enter BigQuery property dataset

2022-03-08 07:58 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigquery/stepsdesign/BigQuerySink.java
> +  public void enterTheBigQuerySinkPropertiesWithIncorrectTable(String table) {
Remove.
Add common definition in BigQueryBase - Enter BigQuery property table {string}

2022-03-08 07:58 UTC, sawantpritam commented on src/e2e-test/features/bigquery/sink/BigQuerySinkError.feature
> +    Then Verify the validation error message for invalid temporary bucket
missing newline at the end of file.

2022-03-08 07:58 UTC, sawantpritam commented on src/e2e-test/features/bigquery/source/BigQueryToBigQuery.feature
> +    Then Verify the partition table is created with partitioned on field "bqPartitionFieldTime"
missing newline at the end of file.

2022-03-08 07:58 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigquery/stepsdesign/BigQueryBase.java
> +import java.util.Locale;
remove

2022-03-08 07:58 UTC, sawantpritam commented on src/e2e-test/resources/errorMessage.properties
> +errorMessageIncorrectBQSinkDataset=Dataset name can only contain letters (lower or uppercase), numbers and '_'.
Create common error message -
errorMessageIncorrectBQProperty=PROPERTY name can only contain letters (lower or uppercase), numbers and '_'.

2022-03-08 07:58 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/utils/E2ETestConstants.java
> +  public static final String ERROR_MSG_BQ_INCORRECT_DATASET = "errorMessageIncorrectBQSinkDataset";
common ERROR_MSG_BQ_INCORRECT_PROPERTY=errorMessageIncorrectBQProperty

2022-03-09 16:24 UTC, itsmekumari commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +  @Before(order = 1, value = "@BQ_SOURCE_DATATYPE_TEST")
Added the java doc comment.

2022-03-10 06:40 UTC, sawantpritam approved these changes

2022-03-10 06:41 UTC, sawantpritam commented
Please resolve conflicts and squash the commits.

2022-03-10 06:51 UTC, closed without merging