E2e gcs multifile
sawantpritam/google-cloud pull request #25
Opened 2022-04-05 11:50 UTC by sumitsri12

@sawantpritam Please review

2022-04-05 14:01 UTC, sawantpritam requested changes

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/resources/errorMessage.properties
> +errorMessageTemporaryBucket=Bucket name can only contain lowercase letters, numbers, '.', '_', and '-'.
Remove all unused error messages

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/tests/runner/package-info.java
> + * Package contains the tests for the GCP features.
Add proper comment

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/tests/runner/TestRunner.java
> +/*
Change package structure to ->
...plugin/gcsmultifile/runners/TestRunner.java

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/tests/runner/TestRunner.java
> + * Test Runner to execute cases.
Proper comment

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/tests/runner/TestRunner.java
> +        plugin = {"pretty", "html:target/cucumber-html-report", "json:target/cucumber-reports/cucumber.json",
```
plugin = {"pretty", "html:target/cucumber-html-report/gcsmultifile", "json:target/cucumber-reports/cucumber-gcsmultifile.json",
          "junit:target/cucumber-reports/cucumber-gcsmultifile.xml"
```

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +
Remove extra line

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/locators/GCSMultiFileLocators.java
> +  @FindBy(how = How.XPATH, using = "//*[@class='fa fa-remove']")
`//a[@data-testid='close-config-popover']`

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/locators/GCSMultiFileLocators.java
> +  public static WebElement gcsMultiFileProperties;
Not required

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/features/gcsmultifile/GcsMultifile.feature
> +    Then Click on Source
Use from e2e framework -> `When Expand Plugin group in the LHS plugins list: "Source"`

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/features/gcsmultifile/GCSMultifileError.feature
> +    Then Verify required property error for "<property>"
Use from e2e framework -> `Then Validate mandatory property error for "<property>"`

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/features/gcsmultifile/BigQueryTOGCSMultifile_WithMacro.feature
> +    Then Enter GCS MultiFile property "projectId" as macro argument "gcsMultiFileProjectId"
(GCS MultiFile / GcsMultiFile)-> GCSMultiFile

Check all steps..

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/features/gcsmultifile/GcsMultifile.feature
> +    Then Verify data is transferred to target GCS bucket
`Then Verify data is transferred to target GCS bucket with file format "<formatType>"`

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/features/gcsmultifile/GcsMultifile.feature
> +    Then Verify data is transferred to target GCS bucket
No NewLine at the end of file

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +    "@GCS_CSV_SPLIT_FIELD or @GCS_DATATYPE_1_TEST or " +
Remove @GCS_DATATYPE1 and 2 
Not part of this PR

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/actions/GCSMultiFileActions.java
> +    SeleniumHelper.getPropertiesLocators(CdfStudioLocators.class);
Remove not required `SeleniumHelper.getPropertiesLocators(CdfStudioLocators.class);`

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/locators/GCSMultiFileLocators.java
> +  public static WebElement source;
Not required

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +      SeleniumHelper.replaceElementValue(GCSMultiFileLocators.splitField, "");
Use ElementHelper

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +      Assert.fail("Invalid multiFile Mandatory Field " + property);
GCSMultiFile

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +  @Then("Enter the Gcs MultiFile Properties for table {string} and delimited format {string} and delimiter {string}")
Check entire file and remove unused step definitions

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +  @Then("Enter the Gcs MultiFile Properties for path")
-> Enter GCSMultiFile property path

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +  @Then("Enter the Gcs MultiFile Properties for path {string}")
-> Enter GCSMultiFile property path {string}

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/features/gcsmultifile/BigQueryTOGCSMultifile_WithMacro.feature
> +  Scenario:Validate successful records transfer from BigQuery to GCS with macro arguments
to GCSMultiFile

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +  @Then("Verify Content Type Validation")
Verify GCSMultiFile Content Type validation error

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +  @Then("Verify invalid path name error message is displayed for path {string}")
-> Verify GCSMultiFile invalid path name........................

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/features/gcsmultifile/GcsMultifile.feature
> +Feature: MultiFile Sink - Verification of GCS MultiFile Sink plugin
GCSMultiFile Sink - Verification of successful data transfer using GCSMultiFile as sink

2022-04-05 14:01 UTC, sawantpritam commented on src/e2e-test/features/gcsmultifile/GCSMultifileError.feature
> +Feature: GCS MultiFile Plugin Error scenarios
GCSMultiFile Sink - GCS MultiFile Plugin Error scenarios

2022-04-06 09:09 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/tests/runner/package-info.java
> + * Package contains the tests for the GCP features.
Done

2022-04-06 09:09 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/tests/runner/TestRunner.java
> +/*
Done

2022-04-06 09:09 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/tests/runner/TestRunner.java
> + * Test Runner to execute cases.
Done

2022-04-06 09:10 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/tests/runner/TestRunner.java
> +        plugin = {"pretty", "html:target/cucumber-html-report", "json:target/cucumber-reports/cucumber.json",
Done

2022-04-06 09:11 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +
Done

2022-04-06 09:12 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/locators/GCSMultiFileLocators.java
> +  @FindBy(how = How.XPATH, using = "//*[@class='fa fa-remove']")
Done

2022-04-06 09:13 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/locators/GCSMultiFileLocators.java
> +  public static WebElement gcsMultiFileProperties;
Removed

2022-04-06 09:21 UTC, sumitsri12 commented on src/e2e-test/features/gcsmultifile/GcsMultifile.feature
> +    Then Click on Source
changed

2022-04-06 09:22 UTC, sumitsri12 commented on src/e2e-test/features/gcsmultifile/GCSMultifileError.feature
> +    Then Verify required property error for "<property>"
changed

2022-04-06 09:26 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +    "@GCS_CSV_SPLIT_FIELD or @GCS_DATATYPE_1_TEST or " +
@GCS_DATATYPE1 I am using in multifile for datatypes

2022-04-06 09:28 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/actions/GCSMultiFileActions.java
> +    SeleniumHelper.getPropertiesLocators(CdfStudioLocators.class);
Removed

2022-04-06 09:28 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/locators/GCSMultiFileLocators.java
> +  public static WebElement source;
Removed

2022-04-06 09:30 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +      SeleniumHelper.replaceElementValue(GCSMultiFileLocators.splitField, "");
changed

2022-04-06 09:30 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +      Assert.fail("Invalid multiFile Mandatory Field " + property);
Changed

2022-04-06 09:34 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +  @Then("Enter the Gcs MultiFile Properties for table {string} and delimited format {string} and delimiter {string}")
Removed

2022-04-06 09:34 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +  @Then("Enter the Gcs MultiFile Properties for path")
Changed

2022-04-06 09:35 UTC, sumitsri12 commented on src/e2e-test/features/gcsmultifile/BigQueryTOGCSMultifile_WithMacro.feature
> +  Scenario:Validate successful records transfer from BigQuery to GCS with macro arguments
changed

2022-04-06 11:05 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +  @Then("Enter the Gcs MultiFile Properties for path {string}")
Changed

2022-04-06 12:00 UTC, sumitsri12 commented on src/e2e-test/features/gcsmultifile/BigQueryTOGCSMultifile_WithMacro.feature
> +    Then Enter GCS MultiFile property "projectId" as macro argument "gcsMultiFileProjectId"
Changed

2022-04-06 12:01 UTC, sumitsri12 commented on src/e2e-test/features/gcsmultifile/GCSMultifileError.feature
> +Feature: GCS MultiFile Plugin Error scenarios
Done

2022-04-06 12:01 UTC, sumitsri12 commented on src/e2e-test/features/gcsmultifile/GcsMultifile.feature
> +Feature: MultiFile Sink - Verification of GCS MultiFile Sink plugin
Done

2022-04-06 12:04 UTC, sumitsri12 commented on src/e2e-test/features/gcsmultifile/GcsMultifile.feature
> +    Then Verify data is transferred to target GCS bucket
Done

2022-04-06 12:07 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +  @Then("Verify Content Type Validation")
Done

2022-04-06 12:11 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +  @Then("Verify invalid path name error message is displayed for path {string}")
Done

2022-04-06 12:12 UTC, sumitsri12 commented on src/e2e-test/resources/errorMessage.properties
> +errorMessageTemporaryBucket=Bucket name can only contain lowercase letters, numbers, '.', '_', and '-'.
Done

2022-04-07 13:05 UTC, sumitsri12 commented on src/e2e-test/features/gcsmultifile/GcsMultifile.feature
> +    Then Verify data is transferred to target GCS bucket
done

2022-04-07 14:20 UTC, sawantpritam requested changes

2022-04-07 14:20 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +  @Then("Get the count of the records transferred")
Remove unused

2022-04-07 14:20 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +  @Then("Verify data is transferred to target GCS bucket with file format {string}")
Remove unused

2022-04-07 14:20 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +  @Then("Verify required property error for {string}")
Remove unused

2022-04-07 14:20 UTC, sawantpritam commented on src/e2e-test/features/gcsmultifile/GCSMultifileError.feature
> +Feature: GCS MultiFile Plugin Error scenarios
-> Feature: GCSMultiFile Sink - GCS MultiFile Plugin Error scenarios

2022-04-07 14:20 UTC, sawantpritam commented on src/e2e-test/features/gcsmultifile/BigQueryTOGCSMultifile_WithMacro.feature
> +Feature: GCS MultiFile sink - Verification of BigQuery to GCS MultiFile successful data transfer with macro arguments
->  Feature: GCSMultiFile Sink - Verification of BigQuery to GCS MultiFile successful data transfer with macro arguments

2022-04-07 14:59 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +  @Then("Get the count of the records transferred")
removed

2022-04-07 15:02 UTC, sumitsri12 commented on src/e2e-test/java/io/cdap/plugin/gcsmultifile/stepsdesign/GCSMultiFileConnector.java
> +  @Then("Verify data is transferred to target GCS bucket with file format {string}")
using this in file format validation

2022-04-07 15:18 UTC, closed without merging