e2e-bqargumentsetter Test Scenarios
sawantpritam/google-cloud pull request #27
Opened 2022-09-07 11:05 UTC by miqbal001

@sawantpritam Please Review BQArgument Test Scenarios

2022-09-07 14:13 UTC, sawantpritam requested changes

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/features/bigqueryargumentsetter/BigQueryArgumentSetterError.feature
> +    Scenario: verify BigQuery Argument Setter plugin properties validation errors for mandatory fields
nit: verify -> Verify

Check all scenarios

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/stepsdesign/BQArgumentSetter.java
> +    @When("Expand Plugin group in the LHS list: {string}")
Remove unnecessary code

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/stepsdesign/BQArgumentSetter.java
> +  @Then("Enter the Arguments Selection Conditions field {string}")
Remove unused

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/stepsdesign/BQArgumentSetter.java
> +  @Then("Enter the Arguments Selection Conditions Field Value {string}")
Remove this step definition.
You can use framework step to enter key value pairs

https://github.com/cdapio/cdap-e2e-tests/blob/727a948be8abdad2dd8d32900c606285195b0e30/src/main/java/stepsdesign/PipelineSteps.java#L496

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/utils/E2ETestConstants.java
> +  public static final String ERROR_MSG_BQARGUMENT_COLUMN_NAME = "errorMessageBlankBQArgumentColumnName";
Remove unused constant.

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +  private static void createSourceBQArgumentTableWithQueries(String bqArgumentCreateTableQueryFile,
Why this method is needed ? where it is used ?

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/features/bigqueryargumentsetter/BigQueryArgumentSetterRuntime.feature
> +    Scenario: verify BigQuery Argument Setter e2e data transfer with source and sink
Verify BigQuery Argument Setter plugin functionality using BigQuery to BigQuery pipeline

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/features/bigqueryargumentsetter/BigQueryArgumentSetterRuntime.feature
> +    Scenario: verify BigQuery Argument Setter e2e data transfer with Multiple Arguments
Verify BigQuery Argument Setter plugin functionality with multiple arguments using BigQuery to BigQuery pipeline

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/actions/BQArgumentSetterActions.java
> +    public static void enterArgumentSelection(String jsonArgumentField) {
-> enterArgumentSelectionConditions

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/actions/BQArgumentSetterActions.java
> +                    entry.getKey().split("#")[0]);
why this # split required ?

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/actions/BQArgumentSetterActions.java
> +    public static void enterListOfFields(int row, String argumentColumns) {
enterListOfFields -> enterArgumentColumn

argumentColumns -> argumentColumn

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/actions/BQArgumentSetterActions.java
> +    public static void clickFieldsAddRowButton(int row) {
clickFieldsAddRowButton -> clickArgumentColumnsAddRowButton

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/locators/BQArgumentSetterLocators.java
> +            "//input[@placeholder='Column name']";
Avoid usage of placeholder in xpath.

Check all.

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/locators/BQArgumentSetterLocators.java
> +  public static WebElement fieldArgumentColumnAddRowButton(int row) {
fieldArgumentColumnAddRowButton -> locateArgumentColumnsAddRowButton

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/locators/BQArgumentSetterLocators.java
> +  public static WebElement listOfArgumentColumns(int row) {
listOfArgumentColumns -> locateArgumentColumn

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/locators/BQArgumentSetterLocators.java
> +  public static WebElement argumentSelectValue(int row) {
argumentSelectValue -> LocateArgumentSelectionConditionValue

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/locators/BQArgumentSetterLocators.java
> +  public static WebElement argumentSelectColumnName(int row) {
argumentSelectColumnName -> LocateArgumentSelectionConditionColumnName

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/locators/BQArgumentSetterLocators.java
> +  public static WebElement fieldArgumentSelectionAddRowButton(int row) {
fieldArgumentSelectionAddRowButton -> locateArgumentSelectionConditionsAddRowButton

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/features/bigqueryargumentsetter/BigQueryArgumentSetterRuntime.feature
> +    @BQ_ArgumentSet_TEST @BQ_Argument_TEST @BQ_SINK_TEST
Why 2 tags `@BQ_ArgumentSet_TEST @BQ_Argument_TEST` required ?

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/runners/TestRunner.java
> +        tags = {"@BigQueryArgumentSetter1"},
BigQueryArgumentSetter1 ???

Have u executed all tests via TestRunner or mvn verify command ??

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/runners/TestRunner.java
> +        features = {"src/e2e-test/features"},
Indent looks incorrect. Please reformat all files in the PR using this settings file - https://cdap.atlassian.net/wiki/spaces/CE/pages/1594098619/Coding+Standard

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/stepsdesign/BQArgumentSetter.java
> +public class BQArgumentSetter implements E2EHelper {
`implements E2EHelper ` not required

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/resources/pluginDataCyAttributes.properties
> +ArgumentServicePath=serviceFilePath
not required

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/resources/pluginDataCyAttributes.properties
> +ArgumentSelectionConditionColumnName=argumentSelectColumnName
Remove unused datacy

Check all

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/resources/pluginParameters.properties
> +bigQueryArgumentInvalidCondition=[{"key":"asgdagj","value":"dskjfs"}]
Add `bqArgumentSetter` prefix instead of `bigQueryArgument` for all properties

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/resources/pluginParameters.properties
> +bigQueryArgumentValidCondition=[{"key":"fhddv","value":""}]
bqArgumentSetterBlankArgSelectionConditionValue

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/resources/pluginParameters.properties
> +bigQueryArgumentValidTableCondition=[{"key":"transaction_uid","value":"10"}]
bqArgumentSetterValidArgSelectionConditionValue

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/resources/pluginParameters.properties
> +bigQueryArgumentValidTableColumn=transaction_uid, unique_key
bqArgumentSetterValidArgumentColumns

2022-09-07 14:13 UTC, sawantpritam commented on src/e2e-test/resources/pluginParameters.properties
> +bigQueryArgumentDatasetName=BigQuery
unused.

Check all properties. Remove unused.

2022-09-08 05:18 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +  private static void createSourceBQArgumentTableWithQueries(String bqArgumentCreateTableQueryFile,
Created two new tables for bqArgument and source, since we cannot use existing ones due to schema mismatch

2022-09-08 05:25 UTC, miqbal001 commented on src/e2e-test/features/bigqueryargumentsetter/BigQueryArgumentSetterRuntime.feature
> +    @BQ_ArgumentSet_TEST @BQ_Argument_TEST @BQ_SINK_TEST
@BQ_ArgumentSet_TEST for Argument setter and @BQ_Argument_TEST for source

2022-09-08 05:25 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/runners/TestRunner.java
> +        tags = {"@BigQueryArgumentSetter1"},
Test runner

2022-09-08 06:05 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/stepsdesign/BQArgumentSetter.java
> +public class BQArgumentSetter implements E2EHelper {
done

2022-09-08 08:33 UTC, miqbal001 commented on src/e2e-test/resources/pluginParameters.properties
> +bigQueryArgumentValidTableCondition=[{"key":"transaction_uid","value":"10"}]
Removed not in use

2022-09-08 08:43 UTC, miqbal001 commented on src/e2e-test/resources/pluginParameters.properties
> +bigQueryArgumentValidTableColumn=transaction_uid, unique_key
Removed not in use

2022-09-08 08:44 UTC, miqbal001 commented on src/e2e-test/resources/pluginParameters.properties
> +bigQueryArgumentDatasetName=BigQuery
Removed unused

2022-09-08 08:45 UTC, miqbal001 commented on src/e2e-test/resources/pluginParameters.properties
> +bigQueryArgumentValidCondition=[{"key":"fhddv","value":""}]
Changed

2022-09-08 08:45 UTC, miqbal001 commented on src/e2e-test/resources/pluginParameters.properties
> +bigQueryArgumentInvalidCondition=[{"key":"asgdagj","value":"dskjfs"}]
Changes made successfully

2022-09-08 08:47 UTC, miqbal001 commented on src/e2e-test/resources/pluginDataCyAttributes.properties
> +ArgumentSelectionConditionColumnName=argumentSelectColumnName
Removed unused datacy

2022-09-08 08:48 UTC, miqbal001 commented on src/e2e-test/resources/pluginDataCyAttributes.properties
> +ArgumentServicePath=serviceFilePath
Removed

2022-09-08 08:48 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/runners/TestRunner.java
> +        tags = {"@BigQueryArgumentSetter1"},
Changes made Successfully

2022-09-08 08:55 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/locators/BQArgumentSetterLocators.java
> +  public static WebElement listOfArgumentColumns(int row) {
Changes done

2022-09-08 08:57 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/locators/BQArgumentSetterLocators.java
> +  public static WebElement fieldArgumentColumnAddRowButton(int row) {
Changes Done

2022-09-08 08:58 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/locators/BQArgumentSetterLocators.java
> +  public static WebElement argumentSelectValue(int row) {
Changes Done

2022-09-08 08:59 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/locators/BQArgumentSetterLocators.java
> +  public static WebElement argumentSelectColumnName(int row) {
Changes Done

2022-09-08 08:59 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/locators/BQArgumentSetterLocators.java
> +  public static WebElement fieldArgumentSelectionAddRowButton(int row) {
Changes Done

2022-09-08 09:03 UTC, miqbal001 commented on src/e2e-test/features/bigqueryargumentsetter/BigQueryArgumentSetterError.feature
> +    Scenario: verify BigQuery Argument Setter plugin properties validation errors for mandatory fields
Changes Done

2022-09-08 09:04 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/stepsdesign/BQArgumentSetter.java
> +    @When("Expand Plugin group in the LHS list: {string}")
Changes Done

2022-09-08 09:04 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/stepsdesign/BQArgumentSetter.java
> +  @Then("Enter the Arguments Selection Conditions field {string}")
Removed

2022-09-08 09:05 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/utils/E2ETestConstants.java
> +  public static final String ERROR_MSG_BQARGUMENT_COLUMN_NAME = "errorMessageBlankBQArgumentColumnName";
Removed unused constant.

2022-09-08 09:05 UTC, miqbal001 commented on src/e2e-test/features/bigqueryargumentsetter/BigQueryArgumentSetterRuntime.feature
> +    Scenario: verify BigQuery Argument Setter e2e data transfer with source and sink
Changes Mane Successfully

2022-09-08 09:05 UTC, miqbal001 commented on src/e2e-test/features/bigqueryargumentsetter/BigQueryArgumentSetterRuntime.feature
> +    Scenario: verify BigQuery Argument Setter e2e data transfer with Multiple Arguments
Done

2022-09-08 09:06 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/actions/BQArgumentSetterActions.java
> +    public static void enterArgumentSelection(String jsonArgumentField) {
Changes Done

2022-09-08 09:09 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/actions/BQArgumentSetterActions.java
> +    public static void enterListOfFields(int row, String argumentColumns) {
Changes Made

2022-09-08 09:10 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/actions/BQArgumentSetterActions.java
> +    public static void clickFieldsAddRowButton(int row) {
Changes Done

2022-09-08 09:51 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/stepsdesign/BQArgumentSetter.java
> +  @Then("Enter the Arguments Selection Conditions Field Value {string}")
Removed Previous Step replaced with framework step

2022-09-09 04:24 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/actions/BQArgumentSetterActions.java
> +                    entry.getKey().split("#")[0]);
This Step covered by Surya need clarification

2022-09-09 04:24 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/runners/TestRunner.java
> +        features = {"src/e2e-test/features"},
Code Reformatted

2022-09-09 09:39 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/stepsdesign/BQArgumentSetter.java
> +    @When("Expand Plugin group in the LHS list: {string}")
It is not removed.

2022-09-09 09:44 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/stepsdesign/BQArgumentSetter.java
> +  @Then("Enter the Arguments Selection Conditions Field Value {string}")
Step definition not removed. And I can still see its being used in one scenario. https://github.com/sawantpritam/google-cloud/blob/6d89c2d9492c779cde1eaa9dc8133ab587ccb138/src/e2e-test/features/bigqueryargumentsetter/BigQueryArgumentSetterError.feature#L26

2022-09-09 09:58 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +  private static void createSourceBQArgumentTableWithQueries(String bqArgumentCreateTableQueryFile,
Remove this method. Not required.

2022-09-09 09:58 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/actions/BQArgumentSetterActions.java
> +                    entry.getKey().split("#")[0]);
You are not passing # separated values.. It is not required in your case.

2022-09-09 09:58 UTC, sawantpritam commented on src/e2e-test/features/bigqueryargumentsetter/BigQueryArgumentSetterRuntime.feature
> +    @BQ_ArgumentSet_TEST @BQ_Argument_TEST @BQ_SINK_TEST
As discussed use existing tag for Source And rename Argument setter tag

2022-09-09 09:58 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/runners/TestRunner.java
> +        features = {"src/e2e-test/features"},
Still indent looks incorrect.

2022-09-09 10:00 UTC, sawantpritam commented on src/e2e-test/resources/pluginParameters.properties
> +bigQueryArgumentDatasetName=BigQuery
All unused properties not removed.  Check all again.
i.e `bqArgumentSetterIncorrectDataset`

2022-09-09 10:24 UTC, sawantpritam requested changes

2022-09-09 10:24 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/actions/BQArgumentSetterActions.java
> +import io.cdap.plugin.gcp.common.SourceOutputFormatProvider;
Remove unused import.

Optimise imports in all files in this PR.

2022-09-12 06:14 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +  private static void createSourceBQArgumentSetTableWithQueries(String bqArgumentSetCreateTableQueryFile,
Remove this method.

2022-09-12 06:14 UTC, sawantpritam commented on src/e2e-test/resources/pluginParameters.properties
> +bigQueryArgumentDatasetName=BigQuery
All unused properties still not removed. Check all again.
`bqArgumentSetterDataSetSink`

2022-09-12 06:27 UTC, sawantpritam requested changes

2022-09-12 06:27 UTC, sawantpritam commented on src/e2e-test/resources/pluginParameters.properties
> +bqArgumentCreateTableQueryFile=testdata/BigQuery/BigQueryArgumentCreateTableQuery.txt
Add `bqArgumentSetter` prefix to both(create, insert) query file properties
Also add it to filename BigQueryArgumentCreateTableQuery.txt -> BigQueryArgumentSetterCreateTableQuery.txt

And Remove 2 unused query file properties (bqArgumentSetCreateTableQueryFile and bqArgumentSetInsertDataQueryFile), also remove unused txt query files.

2022-09-12 06:27 UTC, sawantpritam commented on src/e2e-test/features/bigqueryargumentsetter/BigQueryArgumentSetterError.feature
> +    @BQ_SOURCE_DATATYPE_TEST
Remove unnecessary tag

2022-09-12 06:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +  @Before(order = 1, value = "@BQ_Argument_TEST")
Remove ununsed tags code.

2022-09-12 06:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +  @Before(order = 1, value = "@BQ_Argument_Setter_TEST")
@BQ_Argument_Setter_TEST-> `@BQ_ARGUMENT_SETTER_TEST`

2022-09-12 06:27 UTC, sawantpritam commented on src/e2e-test/features/bigqueryargumentsetter/BigQueryArgumentSetterError.feature
> +  Feature: BigQuery Argument Setter - Validate BigQuery Argument Setter Plugin Error Scenarios
Check indent.

2022-09-12 06:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/runners/TestRunner.java
> +        features = {"src/e2e-test/features"},
Still indent looks incorrect.

2022-09-12 09:27 UTC, sawantpritam requested changes

2022-09-12 09:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> -          if (serviceAccountType.equalsIgnoreCase("FilePath")) {
Do not change existing code.

2022-09-12 09:27 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> -                       "'SERVICE_ACCOUNT_TYPE' with invalid value: '" + serviceAccountType + "'. " +
Do not change existing code.

2022-09-12 09:29 UTC, sawantpritam commented
Please work on all unresolved comments.... check hidden conversations...there are few unresolved comments.

ALSO ALWAYS MAKE SURE TO EXECUTE TESTS AND VERIFY ALL TESTS ARE PASSING BEFORE PUSING CHANGES. Tests Failing please check.

2022-09-14 06:26 UTC, sawantpritam requested changes

2022-09-14 06:26 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> +  private static void createSourceBQArgumentTableWithQueries(String bqArgumentSetterCreateTableQueryFile,
Remove this method.

2022-09-14 06:26 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> -                       "'SERVICE_ACCOUNT_TYPE' with invalid value: '" + serviceAccountType + "'. " +
Do not change existing code.

2022-09-14 06:26 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/locators/BQArgumentSetterLocators.java
> +            "//input[@placeholder='Column name']";
Avoid placeholder.

2022-09-14 06:26 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/actions/BQArgumentSetterActions.java
> +    public static void enterArgumentSelectionConditions(String jsonArgumentField) {
Unused method.

2022-09-14 07:05 UTC, sawantpritam requested changes

2022-09-14 07:05 UTC, sawantpritam commented on src/e2e-test/features/bigqueryargumentsetter/BigQueryArgumentSetterRuntime.feature
> +@BigQueryArgumentSetter1
BigQueryArgumentSetter1 ?

2022-09-14 07:05 UTC, sawantpritam commented on src/e2e-test/features/bigqueryargumentsetter/BigQueryArgumentSetterRuntime.feature
> +  @BQ_Argument_Setter_TEST @BQ_SOURCE_TEST @BQ_SINK_TEST
@BQ_Argument_Setter_TEST ?

2022-09-15 06:03 UTC, sawantpritam requested changes

2022-09-15 06:03 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/actions/BQArgumentSetterActions.java
> +import java.util.Map;
Optimize imports.

Check all files.

2022-09-15 06:03 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/locators/BQArgumentSetterLocators.java
> +            "(//div[@data-cy='key'])[1]";
Avoid indexing `[1]`

2022-09-15 06:03 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/runners/TestRunner.java
> +  tags = {"@BigQueryArgumentSetter1"},
@BigQueryArgumentSetter1 ?

2022-09-15 06:03 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/stepsdesign/BQArgumentSetter.java
> +    for (int index = 0; index < fields.length; index++) {
Replace for loop with below code :

```
for (int index = 0; index < fields.length; index++) {
      if (index != 0) {
        BQArgumentSetterActions.clickArgumentColumnsAddRowButton(index - 1);
      }
      BQArgumentSetterActions.enterArgumentColumn(index, fields[index]);
    }
```

2022-09-15 06:03 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java
> -                       "'SERVICE_ACCOUNT_TYPE' with invalid value: '" + serviceAccountType + "'. " +
Do not change existing code... formatting of line no 92 and 93 changed. pls revert.

2022-09-15 06:03 UTC, sawantpritam commented on src/e2e-test/resources/testdata/BigQuery/BigQueryArgumentSetterInsertDataQuery.txt
> +('one','Mohammad','iqbal', 25);
We discussed to use `test_automation` as dataset. Change data.

2022-09-15 06:03 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/runners/package-info.java
> + * Package contains the runner for the GCSDelete features.
GCSDelete ?

2022-09-16 05:01 UTC, sawantpritam requested changes

2022-09-16 05:01 UTC, sawantpritam commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/locators/BQArgumentSetterLocators.java
> +            "//div[@data-cy=\"argumentSelectionConditions\"]//div[@data-cy='key']";
Have u executed tests after xpath update ???

2022-09-16 05:32 UTC, miqbal001 commented on src/e2e-test/java/io/cdap/plugin/bigqueryargumentsetter/locators/BQArgumentSetterLocators.java
> +            "//div[@data-cy=\"argumentSelectionConditions\"]//div[@data-cy='key']";
yes its working fine

2022-09-16 14:22 UTC, sawantpritam approved these changes

2022-09-16 14:24 UTC, sawantpritam commented
Your fork is not up to date, take latest and squash the commits.

2022-10-21 09:38 UTC, closed without merging